### ISSUE TITLE
TwoGigabitEthernet ports not supported

### ISSUE THREAD

**Issue by bladei2gold** [heyglen/network_tech#24]
# Which Syntax?:
interface TwoGigabitEthernet1/0/1
# Expected behavior and actual behavior:
Highlight interface and port settings
# Steps to reproduce the problem:
Tw ports are not highlighted or their port settings
# New Feature Description:
Highlight port settings and ports
# Example Syntax
interface TwoGigabitEthernet1/0/1
 description example
 switchport access vlan 1000
 switchport mode access
 switchport voice vlan 3000
 speed auto 100 1000
 trust device cisco-phone
 auto qos voip cisco-phone
 spanning-tree portfast
 service-policy input AutoQos-4.0-CiscoPhone-Input-Policy
 service-policy output AutoQos-4.0-Output-Policy

**Comment by danieldjewell** [comment]
@bladei2gold The PR I just added only addresses this on IOS syntax (which in the sample you posted looks pretty IOS-y to me 😁) -- not sure about the others

**Comment by heyglen** [comment]
I realized after I merged this this is IOS-XE syntax so I rolled it back. 

IOS-XE is not supported at the moment.

**Comment by danieldjewell** [comment]
I guess I don't know what you mean about specifically IOS-XE syntax? IOS-XE is IOS (just running on top of Linux) ... there *are* a few IOS-XE specific commands relating mostly to software upgrades. (E.g. "request platform software.....") 

That said, IOS-XE like 16.4.x, 16.6.x, etc. is just the newer version of IOS. The CLI syntax is otherwise identical (not any different from say the changes between IOS 12.x and 15.x...) 



IOS-XR is totally different ...

**Comment by jhordindy** [comment]
Any word on when this patch will be merged back in to IOS syntax highlighting?

**Comment by heyglen** [comment]
All commands in the example are now supported in 2.50.0
